[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
lib_deps =  https://github.com/adafruit/Adafruit_nRF52_Arduino
build_flags =
    -DLED_R=15
    -DLED_ON=HIGH
    -DBUTTON1=17
    -DBUTTON2=20
    -DBUTTON3=22
    -DBUTTON4=24
    -DOUT1=2
    -DOUT2=29
    -DPIN_MODE=31

# use this environment for installing Adafruit nRF52 Arduino core libraries
[env:adafruit_feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
lib_deps = https://github.com/adafruit/Adafruit_nRF52_Arduino
build_flags = ; Using the NiceNano with the Adafruit Board, we need to define the necessary pins as in variant.cpp
    -DLED_R=15
    -DLED_ON=HIGH
    -DBUTTON1=17
    -DBUTTON2=20
    -DBUTTON3=22
    -DBUTTON4=24
    -DOUT1=2
    -DOUT2=29
    -DPIN_MODE=31

# use this environment for installing Adafruit nRF52 Arduino core libraries
[env:xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
lib_deps = https://github.com/adafruit/Adafruit_nRF52_Arduino
build_flags = ; Using the NiceNano with the Adafruit Board, we need to define the necessary pins as in variant.cpp
    -DLED_R=26 # internal
    -DLED_B=06 # internal
    -DLED_G=30 # internal
    -DLED_ON=LOW # LEDs are active-low on this board...
    -DBUTTON1=32+11 # P1.11
    -DBUTTON2=5 # P0.5
    -DBUTTON3=0xFF #unused
    -DBUTTON4=0xFF #unused
    -DOUT1=32+15 # P1.15
    -DOUT2=32+13 # P1.13
    -DPIN_MODE=32+12 # P1.12
    -DVBATT_DIVIDER_LOW=14 # P0.14
    -DCHARGE_STATE=17 # P0.17